import CheckOutHeader from "@/components/checkout/Header";
import CheckoutFooter from "@/components/checkout/Footer";
import "../globals.css";

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Root3Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` bg-white`}>
        <CheckOutHeader />
        {children}
        <CheckoutFooter />
      </body>
    </html>
  );
}
